
find_package(pybind11 2.10.4 CONFIG)
if ( NOT pybind11_FOUND )
    message( FATAL_ERROR "-- DGCODE_USECONDABOOSTPYTHON==PYBIND11 but could not find pybind11 package." )
endif()

set( SYSTEM_BOOSTPYTHON_CFLAGS_LIST "" )
set( SYSTEM_BOOSTPYTHON_LINKFLAGS_LIST "" )
set( SYSTEM_BOOSTPYTHON_INCDIR "" )

foreach( tmp ${pybind11_INCLUDE_DIRS} )
  list(APPEND SYSTEM_BOOSTPYTHON_CFLAGS_LIST "-I${tmp}" )
endforeach()
foreach( tmp ${pybind11_DEFINITIONS} )
  list(APPEND SYSTEM_BOOSTPYTHON_CFLAGS_LIST "-D${tmp}" )
endforeach()
foreach( tmp ${pybind11_LIBRARIES} )
  list(APPEND SYSTEM_BOOSTPYTHON_LINKFLAGS_LIST "${tmp}" )
endforeach()
set( SYSTEM_BOOSTPYTHON_FOUND ON )
if ( DG_VERBOSE )
  message("-- boost-python compilation flags : ${SYSTEM_BOOSTPYTHON_CFLAGS_LIST} " )
  message("-- boost-python link flags : ${SYSTEM_BOOSTPYTHON_LINKFLAGS_LIST} " )
  message("-- boost-python headers : ${SYSTEM_BOOSTPYTHON_INCDIR} " )
endif()
