name: Check for new Private Projects commit and run tests

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '55 * * * *'

jobs:
  decide_if_test_run_is_needed:
    runs-on: ubuntu-latest
    outputs:
      runTests: ${{ steps.check_for_new_commits.outputs.isThereNewCommit }}

    steps:
    - name: Download previous artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: last_commit_check
        search_artifacts: true
        if_no_artifact_found: warn

    - name: Get the time of the last run
      run: |
        if [ -f last_commit_check.txt ]; then
          echo "LAST_COMMIT_CHECK_TIME=$(cat last_commit_check.txt)" >> $GITHUB_ENV
        else
          echo "LAST_COMMIT_CHECK_TIME=0" >> $GITHUB_ENV
        fi
      
    - name: Check for new commits
      id: check_for_new_commits
      run: |
        time_string=$(curl --header "PRIVATE-TOKEN: ${{secrets.PRIVATE_PROJ_REPO_API_TOKEN}}" "${{ secrets.PRIVATE_PROJ_REPO_API_URL }}/commits?per_page=1" | jq -r '.[0].created_at')
        echo $(date +%s) > last_commit_check.txt
        lastCommitTime=$(date -d $time_string +%s)
        isThereNewCommit=$(if (( $lastCommitTime > ${{ env.LAST_COMMIT_CHECK_TIME }} )); then echo 1; else echo 0; fi )
        echo "isThereNewCommit=$isThereNewCommit" >> $GITHUB_OUTPUT
        echo $lastCommitTime ${{ env.LAST_COMMIT_CHECK_TIME }} $isThereNewCommit

    - name: Upload check for new commits time (for the next workflow run)
      uses: actions/upload-artifact@v2
      with:
        name: last_commit_check
        path: last_commit_check.txt

  run_test_workflow:
    uses: mctools/dgcode/.github/workflows/run-private-proj-tests.yml@dev-workflows
    needs: decide_if_test_run_is_needed
    if: needs.decide_if_test_run_is_needed.outputs.runTests == 1
