name: Call Private Projects test workflow

on:
  push:
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday
  workflow_dispatch:

jobs:
  privateProjects:
    uses:  mctools/dgcode_actions/.github/workflows/run_private_projects_tests.yml@main
    secrets:
      PRIVATE_PROJ_REPO_URL: ${{ secrets.PRIVATE_PROJ_REPO_URL }}
      PRIVATE_PROJ_REPO_PAT: ${{ secrets.PRIVATE_PROJ_REPO_PAT }}
    with:
      dgcode-branch: '${{ github.ref_name }}'
