name: Call Private Projects test workflow

on:
  push:
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday
  workflow_dispatch:
  workflow_call:

jobs:
  use-test-workflow:
    uses: mctools/dgcode_actions/.github/workflows/run_tests.yml@main
    secrets:
      PRIVATE_PROJ_REPO_URL: ${{ secrets.PRIVATE_PROJ_REPO_URL }}
      PRIVATE_PROJ_REPO_PAT: ${{ secrets.PRIVATE_PROJ_REPO_PAT }}
      DMSC_GITLAB_CERT: ${{ secrets.DMSC_GITLAB_CERT }}
    with:
      pkg-repo: dgcode/dgcode_private_projects
      pkg-repo-branch: main
      dgcode-branch: '${{ github.ref_name }}'
      platform-choice: defaults
