name: Call Private Projects test workflow

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday
  workflow_dispatch:

jobs:
  privateProjects:
    uses:  mctools/dgcode_actions/.github/workflows/run_private_projects_tests.yml@main
    secrets:
      LEGACY_REPO_URL: ${{ secrets.LEGACY_REPO_URL }}
      LEGACY_REPO_PAT: ${{ secrets.LEGACY_REPO_PAT }}
  
